version: '2.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     cpus: 0.9
     cpuset: '0'
     mem_limit: '1g'
     memswap_limit: '0.2g'
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
       - testgalaxy3

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
     restart: always
     cpus: 0.9
     cpuset: '0'
     mem_limit: '1g'
     memswap_limit: '0.2g'
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
     networks:
       - testgalaxy3

volumes:
    db_data: {}
    
networks:
  testgalaxy3:
    driver: bridge
